image:
  file: .gitpod.Dockerfile

tasks:
  - name: Redpanda
    command: >
      docker run -d --pull=always --name=redpanda-1 --rm
      -p 8081:8081
      -p 8082:8082
      -p 9092:9092
      -p 9644:9644
      docker.redpanda.com/vectorized/redpanda:v21.11.16
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false

  - name: Redis
    command: redis-server

  - name: Pre-build
    command: go build ./...

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod